name: Pull Reqeust Check
on:
  push:
    branches: [master]

jobs:
  test:
    name: Inline Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all --all-features
